import Layout from "../src/layout/Layout";
import PageBanner from "../src/layout/PageBanner";
const Policy = () => {
  return (
    <Layout pageTitle={"Privacy Policy"}>
      <PageBanner pageName={"Privacy Policy"} />
      <div className="metaportal_fn_privacy">
        <div className="container small">
          <h3 className="fn__maintitle" data-text="Last updated: March 09, 2024">
            Last updated: March 09, 2024
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
          </p>
          <h3 className="fn__maintitle" data-text="Interpretation and Definitions">
            Interpretation and Definitions
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            Interpretation
          </p>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>
          <p>
            Definitions
          </p>
          <p>
            For the purposes of this Privacy Policy:
          </p>
          <ul>
            <li>
              Account means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
            </li>
            <li>
              Company referred to as either "the Company", "We", "Us" or "Our" in this Agreement refers to Goblin Saga.
            </li>
            <li>
              Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
            </li>
            <li>
              Country refers to: Mexico
            </li>
            <li>
              Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              Personal Data is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              Service refers to the Website.
            </li>
            <li>
              Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
            </li>
            <li>
              Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself for example, the duration of a page visit.
            </li>
            <li>
              Website refers to Goblin Saga, accessible from https://goblinsaga.xyz You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
            </li>
          </ul>
          <h3 className="fn__maintitle" data-text="Collecting and Using Your Personal Data">
            Collecting and Using Your Personal Data
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            Usage Data is collected automatically when using the Service.
          </p>
          <p>
            Usage Data may include information such as Your Device's Internet Protocol address e.g. IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          </p>
          <p>
            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
          </p>
          <p>
            We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
          </p>
          <h3 className="fn__maintitle" data-text="Cookies">
            Cookies
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:
          </p>
          <ul>
            <li>
              Cookies or Browser Cookies. A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
            </li>
            <li>
              Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as web beacons also referred to as clear gifs, pixel tags, and single-pixel gifs that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics for example, recording the popularity of a certain section and verifying system and server integrity.
            </li>
          </ul>
          <p>
            Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. You can learn more about cookies on TermsFeed website article.
          </p>
          <h3
            className="fn__maintitle"
            data-text="Links to Other Websites"
          >
            Links to Other Websites
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
          </p>
          <p>
            We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
          </p>
          <h3 className="fn__maintitle" data-text="Changes to this Privacy Policy">
            Changes to this Privacy Policy
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page
          </p>
          <p>
            We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
          </p>
          <p>
            You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
          </p>
          <h3
            className="fn__maintitle"
            data-text="Contact Us"
          >
            Contact Us
          </h3>
          <div className="fn_cs_divider">
            <div className="divider">
              <span />
              <span />
            </div>
          </div>
          <p>
            info@goblinsaga.xyz
          </p>
        </div>
      </div>
    </Layout>
  );
};
export default Policy;
